# Generated by Django 4.0.4 on 2022-04-23 18:54

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_comments_comment_rename_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to=website.models.upload_location),
        ),
    ]
